"""Streamlit dashboard for cherrysona_property.

The app consumes parquet outputs generated by ``src/etl_realestate.py`` and
mirrors the tab structure proposed in ``코드.md``.
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
import streamlit as st

try:
    import duckdb  # type: ignore
except ImportError:  # pragma: no cover
    duckdb = None

# ---------------------------------------------------------------------------
# Configuration helpers
# ---------------------------------------------------------------------------

DATA_DIR = Path(os.environ.get("CHERRYSONA_DATA_DIR", "data/processed"))
DUCKDB_PATH = os.environ.get("CHERRYSONA_DUCKDB")

MONTHLY_PATH = DATA_DIR / "monthly_basics.parquet"
MOMENTUM_PATH = DATA_DIR / "monthly_momentum.parquet"
VOLATILITY_PATH = DATA_DIR / "monthly_volatility.parquet"
FACT_PARQUET_PATH = DATA_DIR / "transactions.parquet"
FACT_CSV_PATH = DATA_DIR / "transactions.csv"


def normalize_region_columns(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df
    result = df.copy()
    if "sido" in result.columns and "시도" not in result.columns:
        result["시도"] = result["sido"]
    if "시도" in result.columns and "sido" not in result.columns:
        result["sido"] = result["시도"]
    if "sigungu" in result.columns and "시군구" not in result.columns:
        result["시군구"] = result["sigungu"]
    if "시군구" in result.columns and "sigungu" not in result.columns:
        result["sigungu"] = result["시군구"]
    if "eupmyeondong" in result.columns and "읍면동" not in result.columns:
        result["읍면동"] = result["eupmyeondong"]
    if "읍면동" in result.columns and "eupmyeondong" not in result.columns:
        result["eupmyeondong"] = result["읍면동"]
    return result


def normalize_time_columns(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df
    result = df.copy()
    if "yyyymm" in result.columns and "YYYYMM" not in result.columns:
        result.rename(columns={"yyyymm": "YYYYMM"}, inplace=True)
    if "YYYYMM" in result.columns:
        result["YYYYMM"] = pd.to_numeric(result["YYYYMM"], errors="coerce")
    return result


@st.cache_data(show_spinner=False)
def load_fact_frame() -> pd.DataFrame:
    if FACT_CSV_PATH.exists():
        df = pd.read_csv(FACT_CSV_PATH, parse_dates=["계약일자", "snapshot_date", "해제사유발생일"], dtype="object")
        numeric_cols = [
            "전용면적_㎡",
            "면적_평",
            "거래금액_만원",
            "보증금_만원",
            "월세_만원",
            "YYYYMM",
            "연도",
            "월",
            "분기",
            "가격_per_㎡",
            "가격_per_평",
            "환산가_만원",
            "추정매입가_만원",
            "연임대수입_만원",
            "Yield_%",
            "취소여부",
            "date_key",
        ]
        for col in numeric_cols:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce")
        return normalize_time_columns(normalize_region_columns(df))
    if FACT_PARQUET_PATH.exists():
        return normalize_time_columns(normalize_region_columns(pd.read_parquet(FACT_PARQUET_PATH)))
    return pd.DataFrame()


def data_available() -> bool:
    return MONTHLY_PATH.exists() and MOMENTUM_PATH.exists() and VOLATILITY_PATH.exists()


def read_parquet(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Parquet file missing: {path}")
    return pd.read_parquet(path)


@st.cache_data(show_spinner=False)
def load_monthly_basics(
    src_type: str,
    sido: Optional[str] = None,
    sigungu: Optional[str] = None,
    ym_from: Optional[int] = None,
    ym_to: Optional[int] = None,
) -> pd.DataFrame:
    def _cast_numeric(df: pd.DataFrame) -> pd.DataFrame:
        numeric_cols = [
            "YYYYMM",
            "txn_cnt",
            "avg_p_per_m2",
            "std_p_per_m2",
            "avg_yield_pct",
            "cancel_rate",
        ]
        for col in numeric_cols:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce")
        return df

    if DUCKDB_PATH and duckdb is not None:
        query = """
            SELECT * FROM vw_monthly_basics
            WHERE src_type = ?
        """
        params = [src_type]
        if sido:
            query += " AND sido = ?"
            params.append(sido)
        if sigungu:
            query += " AND sigungu = ?"
            params.append(sigungu)
        if ym_from:
            query += " AND yyyymm >= ?"
            params.append(int(ym_from))
        if ym_to:
            query += " AND yyyymm <= ?"
            params.append(int(ym_to))
        with duckdb.connect(DUCKDB_PATH, read_only=True) as con:
            result = normalize_time_columns(
                normalize_region_columns(con.execute(query, params).fetch_df())
            )
            return _cast_numeric(result)

    df = normalize_time_columns(normalize_region_columns(read_parquet(MONTHLY_PATH)))
    mask = df["src_type"] == src_type
    if sido:
        mask &= df["sido"] == sido
    if sigungu:
        mask &= df["sigungu"] == sigungu
    if ym_from:
        mask &= df["YYYYMM"] >= int(ym_from)
    if ym_to:
        mask &= df["YYYYMM"] <= int(ym_to)
    filtered = df.loc[mask].sort_values("YYYYMM")
    return _cast_numeric(filtered)


@st.cache_data(show_spinner=False)
def load_momentum(
    src_type: str,
    sido: Optional[str] = None,
    sigungu: Optional[str] = None,
    ym_from: Optional[int] = None,
    ym_to: Optional[int] = None,
) -> pd.DataFrame:
    def _cast_numeric(df: pd.DataFrame) -> pd.DataFrame:
        for col in [
            "YYYYMM",
            "avg_p_per_m2",
            "avg_p_per_m2_lag3",
            "mom_3m",
        ]:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce")
        return df

    if DUCKDB_PATH and duckdb is not None:
        query = """
            SELECT * FROM vw_monthly_momentum
            WHERE src_type = ?
        """
        params = [src_type]
        if sido:
            query += " AND sido = ?"
            params.append(sido)
        if sigungu:
            query += " AND sigungu = ?"
            params.append(sigungu)
        if ym_from:
            query += " AND yyyymm >= ?"
            params.append(int(ym_from))
        if ym_to:
            query += " AND yyyymm <= ?"
            params.append(int(ym_to))
        with duckdb.connect(DUCKDB_PATH, read_only=True) as con:
            result = normalize_time_columns(
                normalize_region_columns(con.execute(query, params).fetch_df())
            )
            return _cast_numeric(result)

    df = normalize_time_columns(normalize_region_columns(read_parquet(MOMENTUM_PATH)))
    mask = df["src_type"] == src_type
    if sido:
        mask &= df["sido"] == sido
    if sigungu:
        mask &= df["sigungu"] == sigungu
    if ym_from:
        mask &= df["YYYYMM"] >= int(ym_from)
    if ym_to:
        mask &= df["YYYYMM"] <= int(ym_to)
    filtered = df.loc[mask].sort_values("YYYYMM")
    return _cast_numeric(filtered)


@st.cache_data(show_spinner=False)
def load_volatility(src_type: str) -> pd.DataFrame:
    def _cast_numeric(df: pd.DataFrame) -> pd.DataFrame:
        for col in ["YYYYMM", "cv_p_per_m2", "avg_p_per_m2", "std_p_per_m2"]:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce")
        return df

    if DUCKDB_PATH and duckdb is not None:
        with duckdb.connect(DUCKDB_PATH, read_only=True) as con:
            result = normalize_time_columns(
                normalize_region_columns(
                    con.execute(
                        "SELECT * FROM vw_monthly_volatility WHERE src_type = ? ORDER BY yyyymm",
                        [src_type],
                    ).fetch_df()
                )
            )
            return _cast_numeric(result)
    df = normalize_time_columns(normalize_region_columns(read_parquet(VOLATILITY_PATH)))
    filtered = df[df["src_type"] == src_type].sort_values("YYYYMM")
    return _cast_numeric(filtered)


@st.cache_data(show_spinner=False)
def load_explorer(
    src_type: str,
    sido: Optional[str] = None,
    sigungu: Optional[str] = None,
    ym_from: Optional[int] = None,
    ym_to: Optional[int] = None,
    limit: int = 2000,
) -> pd.DataFrame:
    safe_limit = max(1, min(int(limit), 5000))
    if DUCKDB_PATH and duckdb is not None:
        query = """
            SELECT *
            FROM fact_transactions
            WHERE src_type = ?
        """
        params = [src_type]
        if sido:
            query += " AND sido = ?"
            params.append(sido)
        if sigungu:
            query += " AND sigungu = ?"
            params.append(sigungu)
        if ym_from:
            query += " AND yyyymm >= ?"
            params.append(int(ym_from))
        if ym_to:
            query += " AND yyyymm <= ?"
            params.append(int(ym_to))
        query += " ORDER BY yyyymm LIMIT ?"
        params.append(safe_limit)
        with duckdb.connect(DUCKDB_PATH, read_only=True) as con:
            return normalize_time_columns(
                normalize_region_columns(con.execute(query, params).fetch_df())
            )

    df = load_fact_frame()
    mask = df["src_type"] == src_type
    if sido:
        mask &= df["sido"] == sido
    if sigungu:
        mask &= df["sigungu"] == sigungu
    if ym_from:
        mask &= df["YYYYMM"] >= int(ym_from)
    if ym_to:
        mask &= df["YYYYMM"] <= int(ym_to)
    result = df.loc[mask].sort_values("YYYYMM").head(safe_limit)
    return result


@st.cache_data(show_spinner=False)
def load_region_options() -> pd.DataFrame:
    if DUCKDB_PATH and duckdb is not None:
        with duckdb.connect(DUCKDB_PATH, read_only=True) as con:
            df = con.execute(
                "SELECT DISTINCT src_type, sido AS 시도, sigungu AS 시군구 FROM fact_transactions"
            ).fetch_df()
            return df.drop_duplicates().sort_values(["src_type", "시도", "시군구"])

    fact = load_fact_frame()
    if fact.empty:
        return pd.DataFrame(columns=["src_type", "시도", "시군구"])
    return (
        fact[["src_type", "sido", "sigungu"]]
        .rename(columns={"sido": "시도", "sigungu": "시군구"})
        .drop_duplicates()
        .sort_values(["src_type", "시도", "시군구"])
    )


# ---------------------------------------------------------------------------
# UI
# ---------------------------------------------------------------------------

st.set_page_config(page_title="cherrysona Property", layout="wide")
st.title("Hyper-personalized Real Estate Agent")

if not data_available() and not (DUCKDB_PATH and Path(DUCKDB_PATH).exists()):
    st.warning(
        "데이터가 준비되지 않았습니다. 먼저 `python src/etl_realestate.py --data-root ...` 를 실행해 주세요."
    )
    st.stop()

with st.sidebar:
    st.header("필터")
    src_type = st.selectbox(
        "자산 유형",
        options=[
            "apt_trade",
            "apt_lease",
            "offi_trade",
            "offi_lease",
            "comm_trade",
            "row_trade",
            "row_lease",
            "det_trade",
            "det_lease",
        ],
        index=0,
    )

    region_df = load_region_options()
    region_df = region_df[region_df["src_type"] == src_type]
    sido_options = ["(전체)"] + sorted(region_df["시도"].dropna().unique().tolist())
    selected_sido = st.selectbox("시도", options=sido_options)
    if selected_sido == "(전체)":
        selected_sido = None

    sigungu_options = ["(전체)"]
    if selected_sido:
        sigungu_options += (
            region_df[region_df["시도"] == selected_sido]["시군구"].dropna().unique().tolist()
        )
    selected_sigungu = st.selectbox("시군구", options=sigungu_options)
    if selected_sigungu == "(전체)":
        selected_sigungu = None

    date_from = st.text_input("시작 YYYYMM", value="")
    date_to = st.text_input("종료 YYYYMM", value="")
    date_from_int = int(date_from) if date_from.strip() else None
    date_to_int = int(date_to) if date_to.strip() else None

    st.divider()
    st.caption("데이터 디렉터리: %s" % DATA_DIR)
    if DUCKDB_PATH:
        st.caption(f"DuckDB: {DUCKDB_PATH}")


@st.cache_data(show_spinner=False)
def latest_metric(df: pd.DataFrame, column: str, default: float = float("nan")) -> float:
    if df.empty or column not in df.columns:
        return default
    return df[column].dropna().iloc[-1] if not df[column].dropna().empty else default


# ---------------------------------------------------------------------------
# Chart helpers
# ---------------------------------------------------------------------------

def safe_line_chart(df: pd.DataFrame, y_columns: list[str]) -> None:
    subset = df.copy()
    if "YYYYMM" in subset.columns:
        subset["YYYYMM"] = pd.to_numeric(subset["YYYYMM"], errors="coerce")
    for col in y_columns:
        if col in subset.columns:
            subset[col] = pd.to_numeric(subset[col], errors="coerce")
    subset.dropna(subset=y_columns, how="all", inplace=True)
    if subset.empty:
        st.info("시각화할 데이터가 없습니다.")
        return
    chart_data = subset.set_index("YYYYMM")[y_columns]
    chart_data = chart_data.replace([np.inf, -np.inf], np.nan).dropna(how="any")
    if chart_data.empty:
        st.info("시각화할 데이터가 없습니다.")
        return
    st.line_chart(chart_data)


def safe_area_chart(df: pd.DataFrame, y_column: str) -> None:
    if y_column not in df.columns:
        st.info("시각화할 데이터가 없습니다.")
        return
    series = pd.to_numeric(df[y_column], errors="coerce")
    subset = df.copy()
    if "YYYYMM" in subset.columns:
        subset["YYYYMM"] = pd.to_numeric(subset["YYYYMM"], errors="coerce")
    subset[y_column] = series
    subset.dropna(subset=[y_column], inplace=True)
    if subset.empty:
        st.info("시각화할 데이터가 없습니다.")
        return
    chart_data = subset.set_index("YYYYMM")[[y_column]].replace([np.inf, -np.inf], np.nan).dropna()
    if chart_data.empty:
        st.info("시각화할 데이터가 없습니다.")
        return
    st.area_chart(chart_data)


# Tabs defined in 코드.md
(tab_overview, tab_vc, tab_ro, tab_persona, tab_explorer, tab_compare) = st.tabs(
    ["Overview", "VC", "RO", "Persona", "Explorer", "Compare"]
)

with tab_overview:
    st.subheader("개요 (월간 KPI)")
    basics = load_monthly_basics(src_type, selected_sido, selected_sigungu, date_from_int, date_to_int)
    if basics.empty:
        st.info("데이터 없음. 필터를 조정하세요.")
    else:
        cols = st.columns(4)
        cols[0].metric("평균 ㎡당가(만원)", f"{latest_metric(basics, 'avg_p_per_m2', 0):.1f}")
        cols[1].metric("거래량(최근월)", int(latest_metric(basics, "txn_cnt", 0)))
        cols[2].metric("평균 Yield(%)", f"{latest_metric(basics, 'avg_yield_pct', 0):.2f}")
        cols[3].metric(
            "취소율(최근월)",
            f"{latest_metric(basics, 'cancel_rate', 0) * 100:.2f}%",
        )
        renamed = basics.rename(columns={
            "avg_p_per_m2": "평균 ㎡당가",
            "txn_cnt": "거래량",
        })
        safe_line_chart(renamed, ["평균 ㎡당가", "거래량"])

with tab_vc:
    st.subheader("VC 랩 (추천/랭킹)")
    st.caption("가격 경쟁력, 품질, 모멘텀을 활용한 점수화 예시")
    momentum_df = load_momentum(src_type, selected_sido, selected_sigungu, date_from_int, date_to_int)
    if momentum_df.empty:
        st.info("모멘텀 데이터를 찾을 수 없습니다.")
    else:
        safe_area_chart(momentum_df.rename(columns={"avg_p_per_m2": "평균 ㎡당가"}), "평균 ㎡당가")
    st.info("가중치 기반 추천 로직은 추후 SQL/Python 뷰로 확장 예정입니다.")

with tab_ro:
    st.subheader("RO 보드 (리스크 & 운영)")
    basics = load_monthly_basics(src_type, selected_sido, selected_sigungu, date_from_int, date_to_int)
    volatility = load_volatility(src_type)
    if volatility.empty:
        st.info("변동성 데이터를 찾을 수 없습니다.")
    else:
        safe_line_chart(volatility.rename(columns={"cv_p_per_m2": "변동계수"}), ["변동계수"])
    if basics.empty:
        st.info("취소율 데이터를 찾을 수 없습니다.")
    else:
        cancel_df = basics.rename(columns={"cancel_rate": "취소율"})
        subset = cancel_df.copy()
        subset["취소율"] = pd.to_numeric(subset["취소율"], errors="coerce")
        subset.dropna(subset=["취소율"], inplace=True)
        if subset.empty:
            st.info("취소율 데이터를 찾을 수 없습니다.")
        else:
            st.bar_chart(subset.set_index("YYYYMM")["취소율"], height=240)

with tab_persona:
    st.subheader("Persona 보드")
    persona_tabs = st.tabs(["연금형", "상업건물", "실거주 성장", "시세차익형"])
    basics = load_monthly_basics(src_type, selected_sido, selected_sigungu, date_from_int, date_to_int)
    if basics.empty:
        for tab in persona_tabs:
            with tab:
                st.info("데이터가 부족합니다.")
    else:
        top_yield = basics.sort_values("avg_yield_pct", ascending=False).head(20)
        with persona_tabs[0]:
            st.caption("Yield↑, 변동성↓, 취소율↓ 조건을 우선 적용")
            st.dataframe(top_yield[["sido", "sigungu", "eupmyeondong", "YYYYMM", "avg_yield_pct", "cancel_rate"]])
        with persona_tabs[1]:
            st.caption("상업/준상업 구간: 구축 + 저층 후보 체크")
            st.info("추가 필터 (건축년도, 층) 연동 예정")
        with persona_tabs[2]:
            st.caption("실거주 성장형: 면적/준공/층 + 예산 필터")
            st.info("Streamlit 슬라이더로 예산 필터 도입 예정")
        with persona_tabs[3]:
            st.caption("시세차익형: 모멘텀 상위 & 저평가 지역")
            st.info("지도/스캐터 뷰 연결 예정")

with tab_explorer:
    st.subheader("Explorer (원천 레코드)")
    limit = st.number_input("최대 행 수", min_value=100, max_value=10_000, value=2000, step=100)
    explorer_df = load_explorer(
        src_type,
        selected_sido,
        selected_sigungu,
        date_from_int,
        date_to_int,
        limit=int(limit),
    )
    if explorer_df.empty:
        st.info("조건에 해당하는 레코드가 없습니다.")
    else:
        st.dataframe(explorer_df)

with tab_compare:
    st.subheader("Compare (후보 비교)")
    st.info("후보 선택 → KPI 카드/레이더 차트 비교 기능은 후속 구현 예정입니다.")
