"""Streamlit dashboard for cherrysona_property.

The app consumes parquet outputs generated by ``src/etl_realestate.py`` and
mirrors the tab structure proposed in ``코드.md``.
"""
from __future__ import annotations

import os
import sys
import time
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
import streamlit as st

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.utils.duckdb_queries import (
    EXPLORER_COLUMNS,
    fact_transactions as build_fact_transactions_query,
    monthly_basics as build_monthly_basics_query,
    monthly_momentum as build_monthly_momentum_query,
    monthly_volatility as build_monthly_volatility_query,
    region_options as build_region_options_query,
)

try:
    import duckdb  # type: ignore
except ImportError:  # pragma: no cover
    duckdb = None

# ---------------------------------------------------------------------------
# Configuration helpers
# ---------------------------------------------------------------------------

DATA_DIR = Path(os.environ.get("CHERRYSONA_DATA_DIR", "data/processed"))
DUCKDB_PATH = os.environ.get("CHERRYSONA_DUCKDB")
DEBUG_MODE = os.environ.get("CHERRYSONA_DEBUG", "0") in {"1", "true", "TRUE"}
DEBUG_LOG_KEY = "__cherrysona_debug_log__"
MAX_UI_ROWS = int(os.environ.get("CHERRYSONA_UI_MAX_ROWS", "120"))
DEBUG_LOG_PATH_ENV = os.environ.get("CHERRYSONA_DEBUG_LOG")
DEBUG_LOG_PATH = Path(DEBUG_LOG_PATH_ENV).expanduser() if DEBUG_LOG_PATH_ENV else None

if DEBUG_MODE and DEBUG_LOG_PATH:
    try:
        DEBUG_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
        with DEBUG_LOG_PATH.open("a", encoding="utf-8") as fh:
            fh.write("\n--- Streamlit session started at %s ---\n" % time.strftime("%Y-%m-%d %H:%M:%S"))
    except Exception:  # pragma: no cover - logging failures shouldn't break app
        pass

MONTHLY_PATH = DATA_DIR / "monthly_basics.parquet"
MOMENTUM_PATH = DATA_DIR / "monthly_momentum.parquet"
VOLATILITY_PATH = DATA_DIR / "monthly_volatility.parquet"
FACT_PARQUET_PATH = DATA_DIR / "transactions.parquet"
FACT_CSV_PATH = DATA_DIR / "transactions.csv"

def normalize_region_columns(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df
    result = df.copy()
    if "sido" in result.columns and "시도" not in result.columns:
        result["시도"] = result["sido"]
    if "시도" in result.columns and "sido" not in result.columns:
        result["sido"] = result["시도"]
    if "sigungu" in result.columns and "시군구" not in result.columns:
        result["시군구"] = result["sigungu"]
    if "시군구" in result.columns and "sigungu" not in result.columns:
        result["sigungu"] = result["시군구"]
    if "eupmyeondong" in result.columns and "읍면동" not in result.columns:
        result["읍면동"] = result["eupmyeondong"]
    if "읍면동" in result.columns and "eupmyeondong" not in result.columns:
        result["eupmyeondong"] = result["읍면동"]
    return result


def normalize_time_columns(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df
    result = df.copy()
    if "yyyymm" in result.columns and "YYYYMM" not in result.columns:
        result.rename(columns={"yyyymm": "YYYYMM"}, inplace=True)
    if "YYYYMM" in result.columns:
        result["YYYYMM"] = pd.to_numeric(result["YYYYMM"], errors="coerce")
    return result


def sanitize_numeric(df: pd.DataFrame, columns: list[str] | None = None) -> pd.DataFrame:
    if df.empty:
        return df
    result = df.copy()
    target_cols: list[str]
    if columns is not None:
        target_cols = [col for col in columns if col in result.columns]
    else:
        target_cols = [
            col
            for col in result.columns
            if pd.api.types.is_numeric_dtype(result[col])
            or result[col].dtype == object
        ]
    for col in target_cols:
        numeric_series = pd.to_numeric(result[col], errors="coerce")
        if not pd.api.types.is_float_dtype(numeric_series.dtype):
            numeric_series = numeric_series.astype("float64")
        arr = numeric_series.to_numpy(dtype="float64")
        mask = ~np.isfinite(arr)
        if mask.any():
            numeric_series = pd.Series(np.where(mask, np.nan, arr), index=numeric_series.index)
        result[col] = numeric_series
    return result


def trim_for_ui(df: pd.DataFrame, *, sort_column: str = "YYYYMM") -> pd.DataFrame:
    if df.empty or len(df) <= MAX_UI_ROWS:
        return df
    if sort_column in df.columns:
        return df.sort_values(sort_column).tail(MAX_UI_ROWS)
    return df.head(MAX_UI_ROWS)


@st.cache_data(show_spinner=False, ttl=0 if DEBUG_MODE else None)
def load_fact_frame() -> pd.DataFrame:
    if FACT_CSV_PATH.exists():
        df = pd.read_csv(FACT_CSV_PATH, parse_dates=["계약일자", "snapshot_date", "해제사유발생일"], dtype="object")
        numeric_cols = [
            "전용면적_㎡",
            "면적_평",
            "거래금액_만원",
            "보증금_만원",
            "월세_만원",
            "YYYYMM",
            "연도",
            "월",
            "분기",
            "가격_per_㎡",
            "가격_per_평",
            "환산가_만원",
            "추정매입가_만원",
            "연임대수입_만원",
            "Yield_%",
            "취소여부",
            "date_key",
        ]
        for col in numeric_cols:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce")
        result = sanitize_numeric(
            normalize_time_columns(normalize_region_columns(df)),
            columns=numeric_cols,
        )
        debug_log(f"load_fact_frame csv rows={len(result)}")
        return result
    if FACT_PARQUET_PATH.exists():
        result = sanitize_numeric(
            normalize_time_columns(
                normalize_region_columns(pd.read_parquet(FACT_PARQUET_PATH))
            ),
            columns=numeric_cols,
        )
        debug_log(f"load_fact_frame parquet rows={len(result)}")
        return result
    return pd.DataFrame()


def data_available() -> bool:
    return MONTHLY_PATH.exists() and MOMENTUM_PATH.exists() and VOLATILITY_PATH.exists()


def read_parquet(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Parquet file missing: {path}")
    return pd.read_parquet(path)


def debug_log(message: str) -> None:
    if not DEBUG_MODE:
        return
    logs = st.session_state.setdefault(DEBUG_LOG_KEY, [])
    timestamp = time.strftime("%H:%M:%S")
    entry = f"[{timestamp}] {message}"
    logs.append(entry)
    if DEBUG_LOG_PATH:
        try:
            DEBUG_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
            with DEBUG_LOG_PATH.open("a", encoding="utf-8") as fh:
                fh.write(entry + "\n")
        except Exception:  # pragma: no cover - avoid breaking app due to logging
            pass


def clear_debug_log() -> None:
    if DEBUG_LOG_KEY in st.session_state:
        del st.session_state[DEBUG_LOG_KEY]


@st.cache_resource(show_spinner=False, ttl=0 if DEBUG_MODE else None)
def get_duckdb_connection(path: str | None):
    """Return a per-session DuckDB connection managed by Streamlit."""
    if duckdb is None:
        raise RuntimeError("duckdb is not installed; run `pip install duckdb` to enable DB mode")
    if not path:
        raise RuntimeError("CHERRYSONA_DUCKDB env var is missing; cannot open DuckDB database")

    debug_log(f"Opening DuckDB connection -> {path}")
    connection = duckdb.connect(path, read_only=True)

    def _cleanup() -> None:
        try:
            connection.close()
            debug_log("DuckDB connection closed")
        except duckdb.Error:
            pass

    st.on_session_end(_cleanup)
    return connection


def fetch_duckdb(query: str, params: list | tuple | None = None) -> pd.DataFrame:
    """Execute ``query`` against the cached DuckDB connection and return a DataFrame."""
    if duckdb is None or not DUCKDB_PATH:
        raise RuntimeError("DuckDB connection requested but configuration is missing")

    normalized_query = " ".join(query.split())
    debug_log(f"Executing query: {normalized_query} | params={params or []}")
    connection = get_duckdb_connection(DUCKDB_PATH)
    start = time.perf_counter()
    try:
        result = connection.execute(query, params or []).fetch_df()
    finally:
        elapsed_ms = (time.perf_counter() - start) * 1000
        debug_log(f"Query finished in {elapsed_ms:.1f} ms")
    return result


@st.cache_data(show_spinner=False, ttl=0 if DEBUG_MODE else None)
def load_monthly_basics(
    src_type: str,
    sido: Optional[str] = None,
    sigungu: Optional[str] = None,
    ym_from: Optional[int] = None,
    ym_to: Optional[int] = None,
) -> pd.DataFrame:
    def _cast_numeric(df: pd.DataFrame) -> pd.DataFrame:
        numeric_cols = [
            "YYYYMM",
            "txn_cnt",
            "avg_p_per_m2",
            "std_p_per_m2",
            "avg_yield_pct",
            "cancel_rate",
        ]
        return sanitize_numeric(df, numeric_cols)

    if DUCKDB_PATH and duckdb is not None:
        spec = build_monthly_basics_query(
            src_type,
            sido=sido,
            sigungu=sigungu,
            ym_from=ym_from,
            ym_to=ym_to,
        )
        result = normalize_time_columns(
            normalize_region_columns(fetch_duckdb(spec.sql, list(spec.params)))
        )
        result = trim_for_ui(result)
        debug_log(
            "monthly_basics rows=%d filters={sido=%s,sigungu=%s,ym_from=%s,ym_to=%s}" % (
                len(result), sido, sigungu, ym_from, ym_to
            )
        )
        return _cast_numeric(result)

    df = normalize_time_columns(normalize_region_columns(read_parquet(MONTHLY_PATH)))
    mask = df["src_type"] == src_type
    if sido:
        mask &= df["sido"] == sido
    if sigungu:
        mask &= df["sigungu"] == sigungu
    if ym_from:
        mask &= df["YYYYMM"] >= int(ym_from)
    if ym_to:
        mask &= df["YYYYMM"] <= int(ym_to)
    filtered = df.loc[mask].sort_values("YYYYMM")
    filtered = trim_for_ui(filtered)
    debug_log(
        "monthly_basics-parquet rows=%d filters={sido=%s,sigungu=%s,ym_from=%s,ym_to=%s}" % (
            len(filtered), sido, sigungu, ym_from, ym_to
        )
    )
    return _cast_numeric(filtered)


@st.cache_data(show_spinner=False, ttl=0 if DEBUG_MODE else None)
def load_momentum(
    src_type: str,
    sido: Optional[str] = None,
    sigungu: Optional[str] = None,
    ym_from: Optional[int] = None,
    ym_to: Optional[int] = None,
) -> pd.DataFrame:
    def _cast_numeric(df: pd.DataFrame) -> pd.DataFrame:
        numeric_cols = [
            "YYYYMM",
            "avg_p_per_m2",
            "avg_p_per_m2_lag3",
            "mom_3m",
        ]
        return sanitize_numeric(df, numeric_cols)

    if DUCKDB_PATH and duckdb is not None:
        spec = build_monthly_momentum_query(
            src_type,
            sido=sido,
            sigungu=sigungu,
            ym_from=ym_from,
            ym_to=ym_to,
        )
        result = normalize_time_columns(
            normalize_region_columns(fetch_duckdb(spec.sql, list(spec.params)))
        )
        result = trim_for_ui(result)
        debug_log(
            "monthly_momentum rows=%d filters={sido=%s,sigungu=%s,ym_from=%s,ym_to=%s}" % (
                len(result), sido, sigungu, ym_from, ym_to
            )
        )
        return _cast_numeric(result)

    df = normalize_time_columns(normalize_region_columns(read_parquet(MOMENTUM_PATH)))
    mask = df["src_type"] == src_type
    if sido:
        mask &= df["sido"] == sido
    if sigungu:
        mask &= df["sigungu"] == sigungu
    if ym_from:
        mask &= df["YYYYMM"] >= int(ym_from)
    if ym_to:
        mask &= df["YYYYMM"] <= int(ym_to)
    filtered = df.loc[mask].sort_values("YYYYMM")
    filtered = trim_for_ui(filtered)
    debug_log(
        "monthly_momentum-parquet rows=%d filters={sido=%s,sigungu=%s,ym_from=%s,ym_to=%s}" % (
            len(filtered), sido, sigungu, ym_from, ym_to
        )
    )
    return _cast_numeric(filtered)


@st.cache_data(show_spinner=False, ttl=0 if DEBUG_MODE else None)
def load_volatility(
    src_type: str,
    sido: Optional[str] = None,
    sigungu: Optional[str] = None,
    ym_from: Optional[int] = None,
    ym_to: Optional[int] = None,
) -> pd.DataFrame:
    def _cast_numeric(df: pd.DataFrame) -> pd.DataFrame:
        numeric_cols = ["YYYYMM", "cv_p_per_m2", "avg_p_per_m2", "std_p_per_m2"]
        return sanitize_numeric(df, numeric_cols)

    if DUCKDB_PATH and duckdb is not None:
        spec = build_monthly_volatility_query(
            src_type,
            sido=sido,
            sigungu=sigungu,
            ym_from=ym_from,
            ym_to=ym_to,
        )
        result = normalize_time_columns(
            normalize_region_columns(
                fetch_duckdb(spec.sql, list(spec.params))
            )
        )
        result = trim_for_ui(result)
        debug_log(
            "monthly_volatility rows=%d filters={sido=%s,sigungu=%s,ym_from=%s,ym_to=%s}" % (
                len(result), sido, sigungu, ym_from, ym_to
            )
        )
        return _cast_numeric(result)
    df = normalize_time_columns(normalize_region_columns(read_parquet(VOLATILITY_PATH)))
    mask = df["src_type"] == src_type
    if sido:
        mask &= df["sido"] == sido
    if sigungu:
        mask &= df["sigungu"] == sigungu
    if ym_from:
        mask &= df["YYYYMM"] >= int(ym_from)
    if ym_to:
        mask &= df["YYYYMM"] <= int(ym_to)
    filtered = df.loc[mask].sort_values("YYYYMM")
    filtered = trim_for_ui(filtered)
    debug_log(
        "monthly_volatility-parquet rows=%d filters={sido=%s,sigungu=%s,ym_from=%s,ym_to=%s}" % (
            len(filtered), sido, sigungu, ym_from, ym_to
        )
    )
    return _cast_numeric(filtered)


@st.cache_data(show_spinner=False, ttl=0 if DEBUG_MODE else None)
def load_explorer(
    src_type: str,
    sido: Optional[str] = None,
    sigungu: Optional[str] = None,
    ym_from: Optional[int] = None,
    ym_to: Optional[int] = None,
    limit: int = 2000,
    offset: int = 0,
    sample: bool = True,
) -> pd.DataFrame:
    safe_limit = max(1, min(int(limit), 5000))
    safe_offset = max(0, int(offset))
    no_filter = not any([sido, sigungu, ym_from, ym_to])
    effective_sample = sample or no_filter
    if DUCKDB_PATH and duckdb is not None:
        spec = build_fact_transactions_query(
            src_type,
            sido=sido,
            sigungu=sigungu,
            ym_from=ym_from,
            ym_to=ym_to,
            limit=safe_limit,
            offset=safe_offset,
            sample=effective_sample,
        )
        frame = normalize_time_columns(
            normalize_region_columns(fetch_duckdb(spec.sql, list(spec.params)))
        )
        debug_log(
            "explorer rows=%d sample=%s limit=%d offset=%d" % (
                len(frame), effective_sample, safe_limit, safe_offset
            )
        )
        return frame

    df = load_fact_frame()
    mask = df["src_type"] == src_type
    if sido:
        mask &= df["sido"] == sido
    if sigungu:
        mask &= df["sigungu"] == sigungu
    if ym_from:
        mask &= df["YYYYMM"] >= int(ym_from)
    if ym_to:
        mask &= df["YYYYMM"] <= int(ym_to)
    filtered = df.loc[mask].sort_values("YYYYMM")
    columns_present = [col for col in EXPLORER_COLUMNS if col in filtered.columns]
    if effective_sample:
        result = filtered.sample(n=min(safe_limit, len(filtered)), random_state=0)
    else:
        result = filtered.iloc[safe_offset : safe_offset + safe_limit]
    if columns_present:
        result = result[columns_present]
    debug_log(
        "explorer-parquet rows=%d sample=%s limit=%d offset=%d" % (
            len(result), effective_sample, safe_limit, safe_offset
        )
    )
    return result


@st.cache_data(show_spinner=False, ttl=0 if DEBUG_MODE else None)
def load_region_options() -> pd.DataFrame:
    if DUCKDB_PATH and duckdb is not None:
        spec = build_region_options_query()
        df = fetch_duckdb(spec.sql, list(spec.params))
        debug_log(f"region_options rows={len(df)}")
        return df.drop_duplicates().sort_values(["src_type", "시도", "시군구"])

    fact = load_fact_frame()
    if fact.empty:
        return pd.DataFrame(columns=["src_type", "시도", "시군구"])
    fallback = (
        fact[["src_type", "sido", "sigungu"]]
        .rename(columns={"sido": "시도", "sigungu": "시군구"})
        .drop_duplicates()
        .sort_values(["src_type", "시도", "시군구"])
    )
    debug_log(f"region_options-parquet rows={len(fallback)}")
    return fallback


def clear_cached_functions() -> None:
    targets = [
        load_fact_frame,
        load_monthly_basics,
        load_momentum,
        load_volatility,
        load_explorer,
        load_region_options,
    ]
    for fn in targets:
        try:
            fn.clear()
        except Exception:
            pass
    try:
        get_duckdb_connection.clear()
    except Exception:
        pass


# ---------------------------------------------------------------------------
# UI
# ---------------------------------------------------------------------------

st.set_page_config(page_title="cherrysona Property", layout="wide")
st.title("Hyper-personalized Real Estate Agent")

if not data_available() and not (DUCKDB_PATH and Path(DUCKDB_PATH).exists()):
    st.warning(
        "데이터가 준비되지 않았습니다. 먼저 `python src/etl_realestate.py --data-root ...` 를 실행해 주세요."
    )
    st.stop()

with st.sidebar:
    st.header("필터")
    src_type = st.selectbox(
        "자산 유형",
        options=[
            "apt_trade",
            "apt_lease",
            "offi_trade",
            "offi_lease",
            "comm_trade",
            "row_trade",
            "row_lease",
            "det_trade",
            "det_lease",
        ],
        index=0,
    )

    region_df = load_region_options()
    region_df = region_df[region_df["src_type"] == src_type]
    sido_options = ["(전체)"] + sorted(region_df["시도"].dropna().unique().tolist())
    selected_sido = st.selectbox("시도", options=sido_options)
    if selected_sido == "(전체)":
        selected_sido = None

    sigungu_options = ["(전체)"]
    if selected_sido:
        sigungu_options += (
            region_df[region_df["시도"] == selected_sido]["시군구"].dropna().unique().tolist()
        )
    selected_sigungu = st.selectbox("시군구", options=sigungu_options)
    if selected_sigungu == "(전체)":
        selected_sigungu = None

    date_from = st.text_input("시작 YYYYMM", value="")
    date_to = st.text_input("종료 YYYYMM", value="")
    date_from_int = int(date_from) if date_from.strip() else None
    date_to_int = int(date_to) if date_to.strip() else None

    st.divider()
    st.caption("데이터 디렉터리: %s" % DATA_DIR)
    if DUCKDB_PATH:
        st.caption(f"DuckDB: {DUCKDB_PATH}")
    if DEBUG_MODE:
        st.divider()
        st.caption("디버그 모드가 활성화되었습니다 (CHERRYSONA_DEBUG=1)")
        if st.button("캐시 초기화 및 로그 지우기", type="secondary"):
            clear_cached_functions()
            clear_debug_log()
            if hasattr(st, "rerun"):
                st.rerun()
            elif hasattr(st, "experimental_rerun"):
                st.experimental_rerun()
            else:
                st.info("Streamlit을 새로고침해 주세요 (버전이 낮아 자동 새로고침 미지원)")
        logs = st.session_state.get(DEBUG_LOG_KEY, [])
        if logs:
            st.text_area("DuckDB 로그", value="\n".join(logs[-200:]), height=240)
        else:
            st.caption("아직 디버그 로그가 없습니다.")


@st.cache_data(show_spinner=False, ttl=0 if DEBUG_MODE else None)
def latest_metric(df: pd.DataFrame, column: str, default: float = float("nan")) -> float:
    if df.empty or column not in df.columns:
        return default
    return df[column].dropna().iloc[-1] if not df[column].dropna().empty else default


# ---------------------------------------------------------------------------
# Chart helpers
# ---------------------------------------------------------------------------

def safe_line_chart(df: pd.DataFrame, y_columns: list[str]) -> None:
    subset = sanitize_numeric(df, ["YYYYMM", *y_columns])
    subset.dropna(subset=["YYYYMM"], inplace=True)
    subset.dropna(subset=y_columns, how="all", inplace=True)
    if subset.empty:
        st.info("시각화할 데이터가 없습니다.")
        return
    chart_data = (
        subset
        .groupby("YYYYMM", dropna=False)[y_columns]
        .mean()
        .sort_index()
    )
    chart_data = sanitize_numeric(chart_data, y_columns).dropna(how="all")
    if chart_data.empty:
        st.info("시각화할 데이터가 없습니다.")
        return
    st.line_chart(chart_data)


def safe_area_chart(df: pd.DataFrame, y_column: str) -> None:
    if y_column not in df.columns:
        st.info("시각화할 데이터가 없습니다.")
        return
    subset = sanitize_numeric(df, ["YYYYMM", y_column])
    subset.dropna(subset=["YYYYMM"], inplace=True)
    subset.dropna(subset=[y_column], inplace=True)
    if subset.empty:
        st.info("시각화할 데이터가 없습니다.")
        return
    chart_data = (
        subset
        .groupby("YYYYMM", dropna=False)[[y_column]]
        .mean()
        .sort_index()
    )
    chart_data = sanitize_numeric(chart_data, [y_column]).dropna(how="all")
    if chart_data.empty:
        st.info("시각화할 데이터가 없습니다.")
        return
    st.area_chart(chart_data)


# Tabs defined in 코드.md
(tab_overview, tab_vc, tab_ro, tab_persona, tab_explorer, tab_compare) = st.tabs(
    ["Overview", "VC", "RO", "Persona", "Explorer", "Compare"]
)

with tab_overview:
    st.subheader("개요 (월간 KPI)")
    basics = load_monthly_basics(src_type, selected_sido, selected_sigungu, date_from_int, date_to_int)
    if basics.empty:
        st.info("데이터 없음. 필터를 조정하세요.")
    else:
        cols = st.columns(4)
        cols[0].metric("평균 ㎡당가(만원)", f"{latest_metric(basics, 'avg_p_per_m2', 0):.1f}")
        cols[1].metric("거래량(최근월)", int(latest_metric(basics, "txn_cnt", 0)))
        cols[2].metric("평균 Yield(%)", f"{latest_metric(basics, 'avg_yield_pct', 0):.2f}")
        cols[3].metric(
            "취소율(최근월)",
            f"{latest_metric(basics, 'cancel_rate', 0) * 100:.2f}%",
        )
        renamed = basics.rename(columns={
            "avg_p_per_m2": "평균 ㎡당가",
            "txn_cnt": "거래량",
        })
        safe_line_chart(renamed, ["평균 ㎡당가", "거래량"])

with tab_vc:
    st.subheader("VC 랩 (추천/랭킹)")
    st.caption("가격 경쟁력, 품질, 모멘텀을 활용한 점수화 예시")
    momentum_df = load_momentum(src_type, selected_sido, selected_sigungu, date_from_int, date_to_int)
    if momentum_df.empty:
        st.info("모멘텀 데이터를 찾을 수 없습니다.")
    else:
        safe_area_chart(momentum_df.rename(columns={"avg_p_per_m2": "평균 ㎡당가"}), "평균 ㎡당가")
    st.info("가중치 기반 추천 로직은 추후 SQL/Python 뷰로 확장 예정입니다.")

with tab_ro:
    st.subheader("RO 보드 (리스크 & 운영)")
    basics = load_monthly_basics(src_type, selected_sido, selected_sigungu, date_from_int, date_to_int)
    volatility = load_volatility(src_type, selected_sido, selected_sigungu, date_from_int, date_to_int)
    if volatility.empty:
        st.info("변동성 데이터를 찾을 수 없습니다.")
    else:
        safe_line_chart(volatility.rename(columns={"cv_p_per_m2": "변동계수"}), ["변동계수"])
    if basics.empty:
        st.info("취소율 데이터를 찾을 수 없습니다.")
    else:
        cancel_df = basics.rename(columns={"cancel_rate": "취소율"})
        subset = sanitize_numeric(cancel_df, ["YYYYMM", "취소율"])
        subset.dropna(subset=["취소율"], inplace=True)
        if subset.empty:
            st.info("취소율 데이터를 찾을 수 없습니다.")
        else:
            bar_data = (
                subset
                .groupby("YYYYMM", dropna=False)["취소율"]
                .mean()
                .sort_index()
            )
            bar_data = sanitize_numeric(bar_data.to_frame(), ["취소율"])["취소율"].dropna()
            if bar_data.empty:
                st.info("취소율 데이터를 찾을 수 없습니다.")
            else:
                st.bar_chart(bar_data, height=240)

with tab_persona:
    st.subheader("Persona 보드")
    persona_tabs = st.tabs(["연금형", "상업건물", "실거주 성장", "시세차익형"])
    basics = load_monthly_basics(src_type, selected_sido, selected_sigungu, date_from_int, date_to_int)
    if basics.empty:
        for tab in persona_tabs:
            with tab:
                st.info("데이터가 부족합니다.")
    else:
        top_yield = basics.sort_values("avg_yield_pct", ascending=False).head(20)
        if len(top_yield) == 20:
            st.caption("상위 20건까지만 미리보기로 제한됩니다.")
        with persona_tabs[0]:
            st.caption("Yield↑, 변동성↓, 취소율↓ 조건을 우선 적용")
            st.dataframe(
                top_yield[["sido", "sigungu", "eupmyeondong", "YYYYMM", "avg_yield_pct", "cancel_rate"]],
                height=360,
            )
        with persona_tabs[1]:
            st.caption("상업/준상업 구간: 구축 + 저층 후보 체크")
            st.info("추가 필터 (건축년도, 층) 연동 예정")
        with persona_tabs[2]:
            st.caption("실거주 성장형: 면적/준공/층 + 예산 필터")
            st.info("Streamlit 슬라이더로 예산 필터 도입 예정")
        with persona_tabs[3]:
            st.caption("시세차익형: 모멘텀 상위 & 저평가 지역")
            st.info("지도/스캐터 뷰 연결 예정")

with tab_explorer:
    st.subheader("Explorer (원천 레코드)")
    has_filter = any([selected_sido, selected_sigungu, date_from_int, date_to_int])
    with st.form("explorer_form", border=False):
        limit = st.number_input(
            "최대 행 수",
            min_value=100,
            max_value=2_000,
            value=100,
            step=50,
        )
        offset = st.number_input(
            "오프셋",
            min_value=0,
            value=0,
            step=250,
            help="페이지 이동에 이용됩니다. 샘플 모드 해제 시에만 적용돼요.",
        )
        sample_mode = st.checkbox(
            "랜덤 샘플로 보기",
            value=True,
            help="필터가 넓을 때는 샘플 모드가 안전합니다.",
        )
        submitted = st.form_submit_button("미리보기")

    if not submitted:
        st.info("조건을 설정하고 '미리보기' 버튼을 눌러 주세요.")
    else:
        effective_sample = sample_mode or not has_filter
        if not sample_mode and not has_filter:
            st.warning("필터가 없어 랜덤 샘플로 자동 전환했습니다.")
        explorer_df = load_explorer(
            src_type,
            selected_sido,
            selected_sigungu,
            date_from_int,
            date_to_int,
            limit=int(limit),
            offset=int(offset),
            sample=effective_sample,
        )
        if explorer_df.empty:
            st.info("조건에 해당하는 레코드가 없습니다.")
        else:
            caption = (
                f"총 {len(explorer_df):,}건 미리보기 (최대 100행). "
                + (
                    "랜덤 샘플입니다."
                    if effective_sample
                    else f"오프셋 {offset:,}부터 표시합니다."
                )
            )
            st.caption(caption)
            st.dataframe(explorer_df.head(100), height=400)
            if len(explorer_df) >= int(limit):
                st.caption("전체 데이터를 내려받으려면 CSV/Parquet 파일을 직접 열어 확인하세요.")

with tab_compare:
    st.subheader("Compare (후보 비교)")
    st.info("후보 선택 → KPI 카드/레이더 차트 비교 기능은 후속 구현 예정입니다.")
